---
  kind: "Service"
  apiVersion: "v1"
  metadata:
    labels:
      app: "mimir"
    # this name is accessible via cluster DNS
    # ("mimir" or "mimir.<namespace>.svc.cluster.local")
    name: "mimir"
    namespace: abuse-api-prod
  spec:
    ports:
      -
        name: "mimir"
        port: 5000
        targetPort: 5000
    selector:
      app: "mimir"