---
apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "mimir"
  namespace: "mimir-api-ote"
spec:
  tls:
    - hosts:
      - "mimir.int.ote-godaddy.com"
      secretName: tls-mimir
  rules:
  - host: "mimir.int.ote-godaddy.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: "mimir"
          servicePort: 5000